# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mqc3_cloud/program/v1/quantum_program.proto
# Protobuf Python Version: 5.27.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    0,
    '',
    'mqc3_cloud/program/v1/quantum_program.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ....mqc3_cloud.program.v1 import circuit_pb2 as mqc3__cloud_dot_program_dot_v1_dot_circuit__pb2
from ....mqc3_cloud.program.v1 import graph_pb2 as mqc3__cloud_dot_program_dot_v1_dot_graph__pb2
from ....mqc3_cloud.program.v1 import machinery_pb2 as mqc3__cloud_dot_program_dot_v1_dot_machinery__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+mqc3_cloud/program/v1/quantum_program.proto\x12\x15mqc3_cloud.program.v1\x1a#mqc3_cloud/program/v1/circuit.proto\x1a!mqc3_cloud/program/v1/graph.proto\x1a%mqc3_cloud/program/v1/machinery.proto\"\xbe\x02\n\x0eQuantumProgram\x12\x43\n\x06\x66ormat\x18\x01 \x01(\x0e\x32+.mqc3_cloud.program.v1.RepresentationFormatR\x06\x66ormat\x12H\n\x07\x63ircuit\x18\x02 \x01(\x0b\x32,.mqc3_cloud.program.v1.CircuitRepresentationH\x00R\x07\x63ircuit\x12\x42\n\x05graph\x18\x03 \x01(\x0b\x32*.mqc3_cloud.program.v1.GraphRepresentationH\x00R\x05graph\x12N\n\tmachinery\x18\x04 \x01(\x0b\x32..mqc3_cloud.program.v1.MachineryRepresentationH\x00R\tmachineryB\t\n\x07payload\"\xf9\x03\n\x14QuantumProgramResult\x12K\n\x0e\x63ircuit_result\x18\x01 \x01(\x0b\x32$.mqc3_cloud.program.v1.CircuitResultR\rcircuitResult\x12\x45\n\x0cgraph_result\x18\x02 \x01(\x0b\x32\".mqc3_cloud.program.v1.GraphResultR\x0bgraphResult\x12Q\n\x10machinery_result\x18\x03 \x01(\x0b\x32&.mqc3_cloud.program.v1.MachineryResultR\x0fmachineryResult\x12Q\n\x0e\x63ompiled_graph\x18\x04 \x01(\x0b\x32*.mqc3_cloud.program.v1.GraphRepresentationR\rcompiledGraph\x12]\n\x12\x63ompiled_machinery\x18\x05 \x01(\x0b\x32..mqc3_cloud.program.v1.MachineryRepresentationR\x11\x63ompiledMachinery\x12H\n\rcircuit_state\x18\x06 \x03(\x0b\x32#.mqc3_cloud.program.v1.BosonicStateR\x0c\x63ircuitState*\xa6\x01\n\x14RepresentationFormat\x12%\n!REPRESENTATION_FORMAT_UNSPECIFIED\x10\x00\x12!\n\x1dREPRESENTATION_FORMAT_CIRCUIT\x10\x01\x12\x1f\n\x1bREPRESENTATION_FORMAT_GRAPH\x10\x02\x12#\n\x1fREPRESENTATION_FORMAT_MACHINERY\x10\x03\x42\xa2\x01\n\x19\x63om.mqc3_cloud.program.v1B\x13QuantumProgramProtoP\x01\xa2\x02\x03MPX\xaa\x02\x14Mqc3Cloud.Program.V1\xca\x02\x14Mqc3Cloud\\Program\\V1\xe2\x02 Mqc3Cloud\\Program\\V1\\GPBMetadata\xea\x02\x16Mqc3Cloud::Program::V1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mqc3_cloud.program.v1.quantum_program_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031com.mqc3_cloud.program.v1B\023QuantumProgramProtoP\001\242\002\003MPX\252\002\024Mqc3Cloud.Program.V1\312\002\024Mqc3Cloud\\Program\\V1\342\002 Mqc3Cloud\\Program\\V1\\GPBMetadata\352\002\026Mqc3Cloud::Program::V1'
  _globals['_REPRESENTATIONFORMAT']._serialized_start=1011
  _globals['_REPRESENTATIONFORMAT']._serialized_end=1177
  _globals['_QUANTUMPROGRAM']._serialized_start=182
  _globals['_QUANTUMPROGRAM']._serialized_end=500
  _globals['_QUANTUMPROGRAMRESULT']._serialized_start=503
  _globals['_QUANTUMPROGRAMRESULT']._serialized_end=1008
# @@protoc_insertion_point(module_scope)
