[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cvzx"
version = "0.1.0"
description = "Measurement-based Quantum Computation with Continuous-variable Cluster states"
readme = "README.md"
requires-python = ">=3.10"

authors = [
  { name = "vardamideslembe@gmail.com" }
]
license = "MIT"

classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering :: Quantum Computing",
  "Typing :: Typed",
]

dependencies = [
  "typing_extensions >= 4.12",
  'tzdata >= 2025.1; platform_system == "Windows"',

  "numpy >= 2.1, < 3",
  "networkx >= 3.4, < 4",
  "sympy >= 1.12",
  "scipy >= 1.10",
  "matplotlib >= 3.7",
  "Pillow >= 9.0",

  "grpcio ~= 1.71",
  "protobuf ~= 5.29",
  "requests >= 2.31, < 3",
]

# [project.urls]

[project.optional-dependencies]
all = []
dev = [
  # Test
  "pytest",
  "allpairspy",
  "pytest-xdist",
  "pytest-cov",
  "pathos",

  # Document
  "sphinx",
  "sphinx_copybutton",
  "sphinxcontrib-bibtex",
  "myst-parser",
  "myst-nb",
  "furo",
  "jupyter",
  "ipykernel",
]
sf = [
  # Note: [sf] is restricted to Python < 3.13 to avoid time-consuming source builds.
  # Legacy versions of scipy (and its dependencies like numpy) do not provide pre-built wheels for Python 3.13+.

  "strawberryfields == 0.23.0; python_version < '3.13'",
  "setuptools < 81.0.0; python_version < '3.13'",       # Required to keep 'pkg_resources', which was removed in newer setuptools and is needed by strawberryfields
  "scipy < 1.14; python_version < '3.13'",              # To avoid import errors with the strawberryfields package
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["cvzx*"]
namespaces = false
exclude = ["build", "tests"]
